name: tiny-workshop
channels:
  - defaults
dependencies:
  - python=3.12
  - numpy
  - matplotlib
  - ipykernel
  - pandas
  - scipy
  - numpy 
  - ipython
  - tqdm
  - pip
  - datasets
  - transformers

